### ISSUE TITLE
Logger used is deprecated

### ISSUE THREAD

**Issue by Nolife999** [InseeFr/ARC#11]
Switching to Log4j2 as it was already declared in project dependencies

**Comment by Nolife999** [comment]
Finally remove log4j2 dependency. ARC uses log4j to fit with spring-core slf4j. Switching to log4j2 will ok if we move to springboot.

**Comment by HealerMikado** [comment]
Try to run the app on a standard tomcat 8.5 and got this error 
```
GRAVE: Exception lors de l'envoi de l'évènement contexte détruit (context destroyed) à l'instance de classe d'écoute [org.springframework.web.context.ContextLoaderListener]
java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.springframework.web.context.ContextCleanupListener.<clinit>(ContextCleanupListener.java:43)
	at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:116)
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4817)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5474)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1423)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1413)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1364)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1185)
	... 12 more
```
But the app run smoothly on an insee tomcat :'(

**Comment by HealerMikado** [comment]
The app in docker work with the commons-logging dependency but doesn't log anything :( hate to fix that
